spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaproject
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      open-in-view: true
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
